# Generated by Django 5.2.6 on 2025-09-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_link",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
