# Generated by Django 5.2.6 on 2025-10-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, default="placeholder.png", null=True, upload_to="projects/"
            ),
        ),
    ]
