# Generated by Django 5.2.6 on 2025-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
