# Generated by Django 5.2.6 on 2025-10-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='about',
            field=models.CharField(blank=True, null=True),
        ),
    ]
