# Generated by Django 5.2.6 on 2025-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_information_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="summary",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
